name: Run tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Install dependencies
      run: go mod tidy

    - name: Run migrations
      run: |
        export DB_SOURCE="postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable"
        make migrateup

    - name: Run tests
      run: |
        export DB_SOURCE="postgresql://root:secret@localhost:5432/simple_bank?sslmode=disable"
        make test
